### ISSUE TITLE
Correcciones y consejos

### ISSUE THREAD

**Issue by Liluminalia** [Fabioo798/202301-W2CH3-Fabio-Dinoia#5]
Buenas Fabio! esta genial y los test todos con resultado correcto esta muy bien! lo único que deberías tener en cuenta a futuro son un par de cosillas:
- El editorconfig! recuerda poner todas las opciones como se ha indicado en clase, ya que a partir de ese estandard se siguen las action! asi que es mas importante de lo que parece, imagínate que entras a una empresa y ellos utilizan X formato, es importante adaptarse a todos, para evitar conflictos, imagínate un trabajo en grupo y cada uno con un formato distinto... conflicto asegurado, intenta modificarlo para la próxima o si te has hecho el boiler, cámbialo para poder partir del general siempre.
- Intenta no hardcodear datos!, por ejemplo en functionLength, cuando indicas que length es 0, seria mas adecuado pasarle un parámetro mas a la función, por ejemplo functionLength(array1, length), y ese parametro "length" ya dentro lo igualas a 0.
- por ultimo, aunq los test estan muy bien, tienes que vigilar el nombre que le pones a los describe y demas, te sera muy util para detectar errores en un futuro mas proximo de lo que parece, RECUERDA!! Given - When - Then, y como recomendacion mencionar en el segundo describe el nombre de la funcion que estas testeando, ya veras como esto en un futuro proximo te da la vida!.

Por lo demás de verdad que esta genial todo y vas muy bien!

**Comment by Fabioo798** [comment]
Buenas Sara,

gracias por el feedback!! sabes donde puedo encontrar las config que nos
pasaron de editorconfig?? por los otros dos puntos me ayudara mucho
aclararlo juntos una vez que vuelva a las clases, si puedes!

saludos,

Il giorno gio 26 gen 2023 alle ore 11:10 Sara Flores <
***@***.***> ha scritto:

**Comment by Liluminalia** [comment]
si claro! en el discord en el apartado de install config hay un repo que paso Alejandro con las configuraciones iniciales, ahi abajo del todo tienes el de editorconfig, 
saludos!
